version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      container_name: frontend
    ports:
      - "3000:3000"  # Map frontend container port to host
    environment:
      - NUXT_PUBLIC_API_URL=http://localhost:5000
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      container_name: backend
    ports:
      - "5000:5000"  # Map backend container port to host
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge